<?php

namespace Plugin\ContactNoticeSlack\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\ContactNoticeSlack\Entity\Config;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends AbstractRepository
{
    /**
     * ConfigRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Config::class);
    }

    /**
     * @param int $id
     *
     * @return null|Config
     */
    public function get($id = 1)
    {
        $Config = $this->find($id);

        if (null === $Config) {
            throw new \Exception('ContactNoticeSlack Config not found. id = '.$id);
        }

        return $this->find($id);
    }
}
